config/routes.rb
Rails.application.routes.draw do
  
    devise_for :users

    resources :movies do
        resources :reviews, except: [:index, :show] 
    end

    root to: "movies#index"
  
end

app/models/movie.rb
class Movie < ActiveRecord::Base

    # Relationships
    belongs_to :user
    has_many :reviews

    has_attached_file :image, styles: { medium: "400x600#" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

    # Validations
    validates :title,
                presence: true,
                length: { minimum: 5 }

    validates :description,
                presence: true,
                length: { minimum: 5 }

    validates :year,
                presence: true

    validates :duration,
                presence: true

    validates :rating,
                presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base

    # Relationships
    belongs_to :user
    belongs_to :movie

    # Validations
    validates :comment,
                presence: true,
                length: { minimum: 5 }

end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    # Relationships
    has_many :movies
    has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    # add 'username' field to permitted params for sign-up
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @reviews = Review.where(movie_id: @movie.id).order("created_at DESC")

    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  # GET /movies/new
  def new
    @movie = current_user.movies.build
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:image, :title, :description, :year, :duration, :rating)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :authenticate_user!
    before_action :set_review, only: [:show, :destroy]
    before_action :set_movie

    # GET /reviews/new
    def new
        @review = Review.new
    end

    # POST /reviews
    # POST /reviews.json
    def create
        @review = Review.new(review_params)
        @review.user_id = current_user.id
        @review.movie_id = @movie.id

        respond_to do |format|
            if @review.save
                format.html { redirect_to @movie, notice: 'Review was successfully created.' }
                format.json { render :show, status: :created, location: @review }
            else
                format.html { render :new }
                format.json { render json: @review.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /reviews/1
    # DELETE /reviews/1.json
    def destroy
        @review.destroy
        
        respond_to do |format|
            format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    
        # Use callbacks to share common setup or constraints between actions.
        def set_review
            @review = Review.find(params[:id])
        end

        def set_movie
            @movie = Movie.find(params[:movie_id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def review_params
            params.require(:review).permit(:rating, :comment)
        end
  end

app/helpers/application_helper.rb
module ApplicationHelper

    def nav_item(path)
        if current_page?(path)
            "active"
        else
            "nav-item"
        end
    end

    def errors_for object
        render :partial => "application/validation_errors", :locals => { :object => object }
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/application/_flash.html.erb
<%= content_tag :div, notice, class: "alert alert-success" if notice %>
<%= content_tag :div, alert, class: "alert alert-danger" if alert %>

app/views/application/_nav.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "TutIMDB", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav">
        <li class="<%= nav_item(root_path) %>"><%= link_to "Movies", root_path %></li>
        <li class="<%= nav_item(new_movie_path) %>"><%= link_to "New Movie", new_movie_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Welcome #{current_user.username}!", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li class="<%= nav_item(new_user_registration_path) %>"><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/application/_validation_errors.html.erb
 <% if object.errors.any? %>
    <div class="alert alert-danger">
        <h4>Ooops! <%= pluralize(object.errors.count, "error") %> occured:</h4>

        <ul>
            <% object.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TutImdb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render "nav" %>

  <div class="container">
    <%= render "flash" %>
    <%= yield %>
  </div>

  <div class="container">
    <hr/>
    <footer>
      <p>&copy; 2016 Lykourgos.</p>
    </footer>
  </div>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, html: { multipart: true } do |f| %>
    
    <%= errors_for @movie %>

    <div class="form-group">
        <%= f.label :image %><br>
        <%= f.file_field :image, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: "form-control", rows: 8 %>
    </div>
    <div class="form-group">
      <%= f.label :year %><br>
      <%= f.number_field :year, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :duration %><br>
      <%= f.text_field :duration, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :rating %><br>
      <%= f.text_field :rating, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit btn_text, class: "btn btn-primary" %>
    </div>
<% end %>

app/views/movies/edit.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <h2>Editing <%= @movie.title %></h2>
                <%= image_tag @movie.image.url(:medium) %>
                <br/>
                <%= render :partial => 'form', :locals => {:btn_text => 'Edit'} %>
            </div>
        </div>
    </div>
</div>

app/views/movies/index.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>TutIMDB</h1>
    <p>This is a web app developed in <em>Ruby on Rails</em> framework and <em>Bootstrap</em>. TutIMDB is quite similar it <strong>IMDB</strong> website for movie reviews.</p>
    <p><%= link_to "Sign up to review", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>

<div class="row">
  <% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag movie.image.url(:medium), class: "image"), movie %>
      </div>
    </div>
  <% end %>
</div>

app/views/movies/new.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <h2>New Movie</h2>
                <%= render :partial => 'form', :locals => {:btn_text => 'Save'} %>
            </div>
        </div>
    </div>
</div>

app/views/movies/show.html.erb
<div class="panel panel-default">
    <div class="panel-body">
      <div class="row">
        <div class="col-md-4">
            <%= image_tag @movie.image.url(:medium) %>
        </div>
        <div class="col-md-6 col-md-offset-1">
            <h2>
                <%= @movie.title %>
                <small>
                    <div class="star-rating" data-score="<%= @avg_review %>"></div>
                    <em><%= @reviews.length %> reviews</em>
                </small>
            </h2>

            <p><strong>Description:</strong></p>
            <p><%= @movie.description %></p>

            <dl class="dl-horizontal">
                <dt>Year:</dt>
                <dd><%= @movie.year %></dd>

                <dt>Duration:</dt>
                <dd><%= @movie.duration %></dd>

                <dt>Rating:</dt>
                <dd><%= @movie.rating %></dd>
            </dl>
          
            <div class="btn-group">
                <%= link_to 'Back', movies_path, class: "btn btn-primary" %>&nbsp;
                <%= link_to 'Edit', edit_movie_path(@movie), class: "btn btn-warning" %>&nbsp;
                <%= link_to 'Delete', movie_path(@movie), method: :delete, class: "btn btn-danger" %>
            </div>

            <hr/>

            <h3>Reviews for this movie</h3>

            <% if @reviews.blank? %>
                <div class="alert alert-warning">
                    <strong class="lead">No reviews have been made for this movie.</strong><br/>
                    Be the first one who will write a review here!
                </div>
            <% else %>
                <ul class="list-unstyled">
                    <% @reviews.each do |review| %>
                        <li>
                            <div class="star-rating" data-score="<%= review.rating %>"></div>&nbsp;
                            <%= review.comment %>
                        </li>
                    <% end %>
                </ul>
            <% end %>

            <%= link_to 'Add Your Review', new_movie_review_path(@movie), class: "btn btn-primary btn-block btn-lg" %>

        </div>
      </div>
    </div>
</div>

app/views/reviews/new.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-body">

                <h2>New Review</h2>

                <%= form_for([@movie, @review]) do |f| %>
                    
                    <%= errors_for @review %>

                    <div class="form-group">
                        <%= f.label :rating %><br>
                        <div id="rate-movie"></div>
                    </div>
                    
                    <div class="form-group">
                        <%= f.label :comment %><br>
                        <%= f.text_area :comment, class: "form-control", rows: 4 %>
                    </div>
                    
                    <div class="form-group">
                        <%= f.submit "Add", class: "btn btn-primary" %>
                    </div>
                <% end %>

                <%= link_to 'Go Back', movie_path(@movie) %>

            </div>
        </div>
    </div>
</div>